### ISSUE TITLE
Memory leak with LinkedHashMap::insert

### ISSUE THREAD

**Issue by TheDan64** [contain-rs/linked-hash-map#110] opened 2022-06-24 19:19 UTC
```rust
fn main() {
    let mut map = LinkedHashMap::new();

    for i in 0..=u32::max_value() {
        map.insert(i, [0; u16::max_value() as usize]);
    }

    drop(map);
}
```

Running [heaptrack](https://github.com/KDE/heaptrack) on the resulting binary, you manage to leak 6GB pretty easily:

![image](https://user-images.githubusercontent.com/3749239/175650843-d6f14771-6055-4a29-b478-1c8368a54fb4.png)

**Comment by Gankra** [comment] 2022-06-24 23:06
I can't see anything in the code that would cause this, and can't reproduce the leaking in my own local testing. Because your example is just purely insert and drop, there's really not a lot of code paths for things to go wrong in.

We have tests that check that destructors get run, and I added some more test ones to double-check that, all pass. I looked around for some type shenanigans that might cause some space to get lost over time, but I don't see any.

Your test tries to allocate like hundreds of GB of RAM at once, which is uh, a little absurd, so I went with something more repetitive to see if memory usage creeped up over time:

```rust
// On MacOS 11.6.7, with 16GB RAM

fn main() {
    let mut total = 0;
    for _ in 0..10_000 {
        let mut map = linked_hash_map::LinkedHashMap::new();

        for i in 0..100 {
            map.insert(i, [0; u16::max_value() as usize]);
        }

        total += map.front().unwrap().0;
    }
    println!("done {total}, sleeping");

    std::thread::sleep(std::time::Duration::from_secs(60));
}
```

Memory usage never really creeps up.

Could you provide more details on your environment?

* rust version
* linked-hash-map version
* OS (Cpu? Surely that's not relevant...)
* how you're building+running your test
* anything weird you're doing with your system swap/allocator?

**Comment by eddyb** [comment] 2022-06-24 23:25
> Your test tries to allocate like 100TB of RAM at once, which is uh, a little absurd, so I went with something more repetitive to see if memory usage creeped up over time:

What if running out of memory *is the point*? Is the `drop(map);` actually reached when `heaptrack` runs the binary? Some kind of output there would be useful to have.
(I'm basically wondering whether an OOM abort would be picked up as "all allocated memory is now leaked")

**Comment by eddyb** [comment] 2022-06-25 07:53
Yeah, okay, OOM perfectly reproduces `heaptrack` thinking it's a leak:
```console
$ echo 'fn main() {
    let mut v = vec![];
    for _ in 0..=u32::MAX {
        v.push(Box::new([0; u16::MAX as usize]));
    }
    println!("pre-drop");
    drop(v);
    println!("post-drop");
}' | rustc - -C opt-level=3 -o oom
$ ./oom
fish: Job 1, './oom' terminated by signal SIGTERM (Polite quit request)
$ heaptrack ./oom
heaptrack output will be written to "/tmp/tmp.aKQvX29Ti9/heaptrack.oom.769734.zst"
/nix/store/pph4dpsb8hs4fzc6yyfqji8z1nd5rw2w-heaptrack-1.3.0/lib/heaptrack/libheaptrack_preload.so
starting application, this might take some time...
Terminated
heaptrack stats:
        allocations:            94145
        leaked allocations:     94123
        temporary allocations:  1
Heaptrack finished! Now run the following to investigate the data:

  heaptrack --analyze "/tmp/tmp.aKQvX29Ti9/heaptrack.oom.769734.zst"

heaptrack_gui detected, automatically opening the file...
```
![image](https://user-images.githubusercontent.com/77424/175764201-20c78844-9fdf-4733-ab06-2e8436277517.png)

**Comment by eddyb** [comment] 2022-06-25 08:00
Another way that you can tell it's running out of memory: see how the graph is nicely linear at the start then starts hitching? That's when it runs out of physical memory and Linux starts swapping.

(I was pretty sure of this anyway, because my laptop became unusable and the test process, alongside with a lot of my GUI apps' processes, kept being pushed into the "disk sleep" state)

![image](https://user-images.githubusercontent.com/77424/175764336-8d650d81-9698-4b33-8979-afd1ac5bbc93.png)

**Comment by Gankra** [comment] 2022-06-25 14:23
gonna go ahead and close this as invalid, feel free to dig deeper and argue otherwise

**Closed by Gankra** 2022-06-25 14:23 UTC

**Comment by TheDan64** [comment] 2022-06-25 20:16
Interesting; I didn't notice any SIGTERM or other signal so I didn't think it was OOM'ing. Will have to dig into it some more. Thank you both for taking a look!

fwiw:
* rust version: 1.61
* linked-hash-map version: 1.2.4
* OS: Ubuntu 20.04
* how you're building+running your test: release mode
* anything weird you're doing with your system swap/allocator?: Nope; default allocator

> Your test tries to allocate like 100TB of RAM at once, which is uh, a little absurd, so I went with something more repetitive to see if memory usage creeped up over time

Oof; intended the ints to be u8's but forget they default to i32 or i64. Still way too big though.

**Comment by eddyb** [comment] 2022-06-25 21:11
The only indication `heaptrack` left in the terminal was the "Terminated" line (because SIGTERM, I guess it would be "Killed" if it had gotten SIGKILL? just checked with `heaptrack $(which echo)` and that one has an empty line instead of "Terminated").

You should definitely add printouts of your own after the part that does all the allocation, so you can confirm it got that far, if tools are going to be ambiguous about various kinds of abnormal process exits.

**Comment by TheDan64** [comment] 2022-06-25 22:09
Thanks for the tips. I'm pretty confident there is a leak here with the insert method as in our application we do see a leak with a clean exit:
![image](https://user-images.githubusercontent.com/3749239/175791859-1159ed9e-dbfd-44c9-b041-b36cd9917e95.png)
But I suppose I'll just have to keep digging to try and repro a MRE.

**Comment by eddyb** [comment] 2022-06-26 10:05
@TheDan64 Can you build using `RUSTFLAGS=-Cmangling-symbol-version=v0 cargo build -Z build-std`?
That should give you much more descriptive symbol names (`cargo install rustfilt` if you need a tool to demangle them if `heaptrack` itself can't do it etc.).

At least knowing all the types involved, they can be investigated independently (though I suppose `insert` isn't one of those methods that are generic in ways that they could cause `K`/`V` methods to allocate).

Also, fuller stack traces would be useful (ideally from debug mode), including details like "is it `malloc` or `realloc`" etc.

**Comment by eddyb** [comment] 2022-06-26 13:49
@TheDan64 Oh another possibility I forgot to bring up, is: could something be leaking the whole `LinkedHashMap`?
Like, `heaptrack` is only telling you where the heap memory was allocated, but what if the `LinkedHashMap` just never gets dropped?

I suppose that should automatically cause `heaptrack` to complain about the `std::collections::HashMap` allocation, but without a `heaptrack` report from debug mode, we won't know for sure whether it's that or the `Node` allocations, that it's talking about (because optimizations would make any of those things look like they're all coming from `LinkedHashMap::insert`).
